In [3]:
import os
import requests
from bs4 import BeautifulSoup
import csv
import pandas as pd
import numpy as np
import time

In [6]:
#Получение списка ссылок

URL="https://dnd.su/bestiary/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
}

response = requests.get(URL, headers=headers)

if response.status_code == 200:

    # Парсим HTML при помощи Beautiful Soup
    soup = BeautifulSoup(response.text, 'html.parser')

monsters_href = []

for data in soup.findAll('a', class_='list-item-wrapper'):
    monsters_href.append("https://dnd.su"+data['href'])

In [37]:

def bestiary_parser(card, count, url):

    df = pd.DataFrame([],columns=['id','name', 'link', 'immunity condition', 
                                       'immunity damage','def','hits','habitat','exp','speed','resist','saving','debility',
                                        'languages', 'feels', 'skill bonus', 'source',
                                       'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma', 'brief inf'])
    
    df.at[count, 'id'] = count+1
    df.at[count, 'name'] = card.find('h2', class_='card-title').text
    df.at[count, 'link'] = url
    df.at[count, 'brief inf'] = card.find('li', class_='size-type-alignment').text

    for card_params in card.findAll('li', class_=''):
        
        try:
    
            if 'Класс Доспеха' in card_params.find('strong').text:
                number = ''.join(c if c.isdigit() else ' ' for c in card_params.text).split()
                df.at[count, 'def'] = int(number[0])
                
            if 'Бонус мастерства' in card_params.find('strong').text:
                df.at[count, 'skill bonus'] = card_params.text.replace('Бонус мастерства ', '')
    
            if 'Чувства' in card_params.find('strong').text:
                df.at[count, 'feels'] = card_params.text.replace('Чувства ', '')
    
            if 'Языки' in card_params.find('strong').text:
                df.at[count, 'languages'] = card_params.text.replace('Языки ', '')
    
            if 'Иммунитет к состоянию' in card_params.find('strong').text:
                df.at[count, 'immunity condition']  = card_params.text.replace('Иммунитет к состоянию ', '')
    
            if 'Иммунитет к урону' in card_params.find('strong').text:
                df.at[count, 'immunity damage']  = card_params.text.replace('Иммунитет к урону ', '')
    
            if 'Хиты' in card_params.find('strong').text:
                df.at[count, 'hits'] = card_params.text.replace('Хиты ', '')
    
            if 'Местность обитания' in card_params.find('strong').text:
                df.at[count, 'habitat'] = card_params.text.replace('Местность обитания ', '')
    
            if 'Опасность' in card_params.find('strong').text:
                df.at[count, 'exp'] = card_params.text.replace('Опасность ', '')
    
            if 'Скорость' in card_params.find('strong').text:
                df.at[count, 'speed'] = card_params.text.replace('Скорость ', '')
    
            if 'Сопротивление урону' in card_params.find('strong').text:
                df.at[count, 'resist'] = card_params.text.replace('Сопротивление урону ', '')
    
            if 'Спасброски' in card_params.find('strong').text:
                df.at[count, 'saving'] = card_params.text.replace('Спасброски ', '')
    
            if 'Уязвимость к урону' in card_params.find('strong').text:
                df.at[count, 'debility'] = card_params.text.replace('Уязвимость к урону ', '')
    
            if 'Источник:' in card_params.find('strong').text:
                df.at[count, 'source'] = card_params.text.replace('Источник: ', '')
                break
    
            if 'Источники:' in card_params.find('strong').text:
                df.at[count, 'source'] = card_params.text.replace('Источники: ', '')
                break
                    
        except Exception as e: 
            print(f'id={count+1} Ошибка {e}')
        
    #Статы       
    for stats in card.findAll('div', class_='stat'):
        number = ''.join(c if c.isdigit() else ' ' for c in stats.text).split()
        number[0]=int(number[0])
        #Отрицательные числа
        if number[0]<=9:
           number[1]=-int(number[1])
        else: number[1]=int(number[1])
        if 'Сил' in stats.text:
            df.at[count, 'strength'] = number
        if 'Лов' in stats.text:
            df.at[count, 'dexterity'] = number
        if 'Тел' in stats.text:
            df.at[count, 'constitution'] = number
        if 'Инт' in stats.text:
            df.at[count, 'intelligence'] = number
        if 'Мдр' in stats.text:
            df.at[count, 'wisdom'] = number
        if 'Хар' in stats.text:
            df.at[count, 'charisma'] = number

    return df

In [8]:

def get_bestiary_html(url):
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')
        
    return soup.find('div', class_='cards-wrapper')

In [88]:

bestiary_df = pd.DataFrame([],columns=['id','name', 'link', 'immunity condition', 
                                       'immunity damage','def','hits','habitat','exp','speed','resist','saving','debility',
                                        'languages', 'feels', 'skill bonus', 'source',
                                       'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma', 'brief inf'])

In [91]:
count=0

for url in monsters_href:
    try:
        card= get_bestiary_html(url)
        bestiary_df = pd.concat([bestiary_df, bestiary_parser(card, count, url)], ignore_index=True)
    except:
        time.sleep(10)
        card= get_bestiary_html(url)
        bestiary_df = pd.concat([bestiary_df, bestiary_parser(card, count, url)], ignore_index=True)

    count+=1

In [4]:
bestiary_df = pd.read_csv('tables/bestiary.csv')

In [156]:

if len(monsters_href) == len(bestiary_df):
    print('Фрейм соответствует по длине\n')


duplicates_series = bestiary_df.duplicated().value_counts()
if duplicates_series[duplicates_series.index==False].iloc[0] == len(bestiary_df):
    print('Дубли строк отсутсвуют')
else: print('Дубли строк присутствуют')

Фрейм соответствует по длине

Дубли строк отсутсвуют

In [117]:
for name in bestiary_df['name'][bestiary_df.duplicated(subset=['name'])]:
    display(bestiary_df[['name','link']][bestiary_df['name']==name])

                      name                                       link
7  Амфисбена [Amphisbaena]  https://dnd.su/bestiary/7169-amphisbaena/
8  Амфисбена [Amphisbaena]  https://dnd.su/bestiary/7498-amphisbaena/

                            name                                       link
164  Большой мимик [Large Mimic]  https://dnd.su/bestiary/6235-large-mimic/
170  Большой мимик [Large Mimic]  https://dnd.su/bestiary/8050-large-mimic/

                   name                                    link
239  Бафомет [Baphomet]  https://dnd.su/bestiary/5861-baphomet/
240  Бафомет [Baphomet]  https://dnd.su/bestiary/6475-baphomet/

               name                                   link
244  Боец [Warrior]  https://dnd.su/bestiary/8017-warrior/
245  Боец [Warrior]  https://dnd.su/bestiary/8023-warrior/

                     name                                     link
298  Верворон [Wereraven]   https://dnd.su/bestiary/949-wereraven/
299  Верворон [Wereraven]  https://dnd.su/bestiary/6905-wereraven/

                  name                                  link
696  Граз'зт [Graz'zt]  https://dnd.su/bestiary/5863-grazzt/
697  Граз'зт [Graz'zt]  https://dnd.su/bestiary/6782-grazzt/

              name                                 link
724  Дерро [Derro]  https://dnd.su/bestiary/5839-derro/
725  Дерро [Derro]  https://dnd.su/bestiary/6587-derro/

                  name                                   link
762  Душитель [Choker]   https://dnd.su/bestiary/6495-choker/
763  Душитель [Choker]  https://dnd.su/bestiary/17390-choker/

,name,link
787,Дуэргар кавалрахни [Duergar Kavalrachni],https://dnd.su/bestiary/6090-duergar-kavalrachni/
788,Дуэргар кавалрахни [Duergar Kavalrachni],https://dnd.su/bestiary/6707-duergar-kavalrachni/

                            name                                        link
797  Дерро савант [Derro Savant]  https://dnd.su/bestiary/5828-derro-savant/
798  Дерро савант [Derro Savant]  https://dnd.su/bestiary/6596-derro-savant/

,name,link
809,Дэтлок умертвие [Deathlock wight],https://dnd.su/bestiary/6584-deathlock-wight/
810,Дэтлок умертвие [Deathlock wight],https://dnd.su/bestiary/17391-deathlock-wight/

                        name                                      link
812  Демогоргон [Demogorgon]  https://dnd.su/bestiary/8033-demogorgon/
928  Демогоргон [Demogorgon]  https://dnd.su/bestiary/5864-demogorgon/
929  Демогоргон [Demogorgon]  https://dnd.su/bestiary/6586-demogorgon/

                        name                                      link
812  Демогоргон [Demogorgon]  https://dnd.su/bestiary/8033-demogorgon/
928  Демогоргон [Demogorgon]  https://dnd.su/bestiary/5864-demogorgon/
929  Демогоргон [Demogorgon]  https://dnd.su/bestiary/6586-demogorgon/

,name,link
931,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/4842-drake-companion/
932,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/14130-drake-companion/
933,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/14131-drake-companion/

,name,link
931,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/4842-drake-companion/
932,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/14130-drake-companion/
933,Дрейк-компаньон [Drake Companion],https://dnd.su/bestiary/14131-drake-companion/

,name,link
1060,Заклинатель (Маг) [Spellcaster (Mage)],https://dnd.su/bestiary/8022-spellcaster-mage/
1061,Заклинатель (Маг) [Spellcaster (Mage)],https://dnd.su/bestiary/8027-spellcaster-mage/

,name,link
1062,Заклинатель (Целитель) [Spellcaster (Healer)],https://dnd.su/bestiary/8014-spellcaster-healer/
1063,Заклинатель (Целитель) [Spellcaster (Healer)],https://dnd.su/bestiary/8025-spellcaster-healer/

,name,link
1080,Икситксачитл вампир [Vampiric Ixitxachitl],https://dnd.su/bestiary/5830-vampiric-ixitxach...
1081,Икситксачитл вампир [Vampiric Ixitxachitl],https://dnd.su/bestiary/5832-vampiric-ixitxach...

                    name                                    link
1127  Йеногу  [Yeenoghu]  https://dnd.su/bestiary/5865-yeenoghu/
1128  Йеногу  [Yeenoghu]  https://dnd.su/bestiary/6938-yeenoghu/

,name,link
1136,Космический хомяк [Space Hamster],https://dnd.su/bestiary/6159-space-hamster/
1172,Космический хомяк [Space Hamster],https://dnd.su/bestiary/8691-space-hamster/

,name,link
1189,Красноклейменный головорез [Red ruffian],https://dnd.su/bestiary/10-red-ruffian/
1190,Красноклейменный головорез [Red ruffian],https://dnd.su/bestiary/12554-red-ruffian/

,name,link
1347,Космический ужас [Cosmic Horror],https://dnd.su/bestiary/8821-cosmic-horror/
1348,Космический ужас [Cosmic Horror],https://dnd.su/bestiary/15694-cosmic-horror/

                   name                                    link
1544  Минлок [Meenlock]  https://dnd.su/bestiary/6835-meenlock/
1545  Минлок [Meenlock]  https://dnd.su/bestiary/8895-meenlock/

,name,link
1559,Мозг в банке [Brain in a Jar],https://dnd.su/bestiary/5758-brain-in-a-jar/
1560,Мозг в банке [Brain in a Jar],https://dnd.su/bestiary/6854-brain-in-a-jar/

,name,link
1713,Неззнар Черный Паук [The Black Spider],https://dnd.su/bestiary/16-the-black-spider/
1714,Неззнар Черный Паук [The Black Spider],https://dnd.su/bestiary/12556-the-black-spider/

                      name                                      link
1741  Некрихор [Necrichor]   https://dnd.su/bestiary/6869-necrichor/
1742  Некрихор [Necrichor]  https://dnd.su/bestiary/13216-necrichor/

            name                                 link
2019  Пич [Pech]  https://dnd.su/bestiary/15252-pech/
2020  Пич [Pech]  https://dnd.su/bestiary/17230-pech/

,name,link
2291,Самка стидера [Female Steeder],https://dnd.su/bestiary/5850-female-steeder/
2292,Самка стидера [Female Steeder],https://dnd.su/bestiary/6708-female-steeder/

                             name                                       link
2649  Фраз-Урб'луу [Fraz-Urb'Luu]  https://dnd.su/bestiary/5866-fraz-urbluu/
2650  Фраз-Урб'луу [Fraz-Urb'Luu]  https://dnd.su/bestiary/6753-fraz-urbluu/

                  name                                   link
2706  Чвинга [Chwinga]  https://dnd.su/bestiary/2642-chwinga/
2707  Чвинга [Chwinga]  https://dnd.su/bestiary/8718-chwinga/

                  name                                  link
2831  Эксперт [Expert]  https://dnd.su/bestiary/8016-expert/
2832  Эксперт [Expert]  https://dnd.su/bestiary/8024-expert/

In [157]:
bestiary_df

,id,name,link,immunity condition,immunity damage,def,hits,habitat,exp,speed,...,feels,skill bonus,source,strength,dexterity,constitution,intelligence,wisdom,charisma,brief inf
0,1,Аластра [Alastrah],https://dnd.su/bestiary/7758-alastrah/,NaN,NaN,10,4 (1к8),NaN,0 (0 или 10 опыта),30 футов,...,пассивное Восприятие 10,+2,«Storm King's Thunder»,"[14, 2]","[10, 0]","[10, 0]","[10, 0]","[10, 0]","[10, 0]","Средний? Великан, нейтральный, именной НИП"
1,2,Альмираж [Almiraj],https://dnd.su/bestiary/1313-almiraj/,NaN,NaN,13,3 (1к6),NaN,0 (0 или 10 опыта),50 футов,...,"тёмное зрение? 30 футов, пассивное Восприятие 14",+2,«Tomb of Annihilation»,"[2, -4]","[16, 3]","[10, 0]","[2, -4]","[14, 2]","[10, 0]","Маленький? Зверь, без мировоззрения"
2,3,Арабэлль [Arabelle],https://dnd.su/bestiary/4679-arabelle/,NaN,NaN,10,2 (1к8 - 2),NaN,0 (0 или 10 опыта),30 футов,...,пассивное Восприятие 10,+2,«Curse of Strahd»,"[10, 0]","[10, 0]","[10, 0]","[10, 0]","[10, 0]","[10, 0]","Средний? Гуманоид (любая раса), любое мировозз..."
3,4,Ааракокра симулякр [Aarakocra Simulacrum],https://dnd.su/bestiary/7756-aarakocra-simulac...,NaN,NaN,12,6 (3к8 - 7),NaN,1/8 (25 опыта),"20 футов, летая 50 футов",...,пассивное Восприятие 15,+2,«Storm King's Thunder»,"[10, 0]","[14, 2]","[10, 0]","[11, 0]","[12, 1]","[11, 0]","Средний? Гуманоид, нейтрально-добрый"
4,5,Ааракокра [Aarakocra],https://dnd.su/bestiary/30-aarakocra/,NaN,NaN,12,13 (3к8),горы,1/4 (50 опыта),"20 футов, летая 50 футов",...,пассивное Восприятие 15,+2,«Monster manual»,"[10, 0]","[14, 2]","[10, 0]","[11, 0]","[12, 1]","[11, 0]","Средний? Гуманоид, нейтрально-добрый"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2863,2864,Янтарный голем [Amber Golem],https://dnd.su/bestiary/4676-amber-golem/,"паралич?, очарование?, отравление?, окаменение...","психическая энергия, яд; дробящий, колющий, ру...",17,178 (17к10 + 85),NaN,10 (5900 опыта),30 футов,...,"тёмное зрение? 120 футов, пассивное Восприятие 10",+4,«Curse of Strahd»,"[22, 6]","[9, -1]","[20, 5]","[3, -4]","[11, 0]","[1, -5]","Большой? Конструкт, без мировоззрения"
2864,2865,Ягнолот [Yagnoloth],https://dnd.su/bestiary/7073-yagnoloth/,отравление?,"кислота, яд",17,147 (14к10 + 70),город,11 (7200 опыта),40 футов,...,"слепое зрение? 60 футов, тёмное зрение? 60 фут...",+4,«Mordenkainen Presents: Monsters of the Multiv...,"[19, 4]","[14, 2]","[21, 5]","[16, 3]","[15, 2]","[18, 4]","Большое? Исчадие (юголот), обычно нейтрально-злое"
2865,2866,Ясновидящий свежеватель разума [Mind Flayer Cl...,https://dnd.su/bestiary/12510-mind-flayer-clai...,"испуг?, ослепление?, очарование?",NaN,15,156 (24к8 + 48),NaN,11 (7200 опыта),"30 футов, летая 60 футов (парит)",...,"истинное зрение? 15 футов, тёмное зрение? 120 ...",+4,«Phandelver and Below: The Shattered Obelisk»,"[11, 0]","[12, 1]","[15, 2]","[21, 5]","[17, 3]","[18, 4]","Средняя? Аберрация, законно-злая"
2866,2867,Ярость Костччи [Fury of Kostchtchie],https://dnd.su/bestiary/12156-fury-of-kostchtc...,"испуг?, отравление?, очарование?",холод,16,216 (16к12 + 112),NaN,14 (11 500 опыта),40 футов,...,"тёмное зрение? 120 футов, пассивное Восприятие 16",+5,«Bigby Presents: Glory of the Giants»,"[26, 8]","[10, 0]","[25, 7]","[10, 0]","[12, 1]","[11, 0]","Огромное? Исчадие (Демон), обычно хаотично-злое"
2867,2868,Ян-Си-Бин [Yan-C-Bin],https://dnd.su/bestiary/3659-yan-c-bin/,"окаменение?, опутанность?, отравление?, сбиван...","звук, электричество, яд",22,283 (21к12 + 147),NaN,18 (20 000 опыта),"50 футов, летая 150 футов",...,"слепое зрение? 120 футов, пассивное Восприятие 15",+6,«Princes of the Apocalypse»,"[18, 4]","[24, 7]","[24, 7]","[16, 3]","[21, 5]","[23, 6]","Огромный? Элементаль, нейтрально-злой, именной..."

In [93]:
bestiary_df.to_csv('tables/bestiary.csv', index=False)